---
title: "Experience"
output: 
  html_document:
    toc: true
    toc_float: true
---
# {.tabset}

I am a current Masters in Public Health Candidate in the Department of Population and Family Health at the Mailman School of Public Health at Columbia University. My focus is in Public Health Research Methods and my goal is to pursue a career in research and public health program evaluation. My main interests include food and nutrition, the built environment, and their impact on chronic disease outcomes.

## Education

**Columbia University, Mailman School of Public Health**  
*New York, NY*  
*Expected Graduation: May 2021*

* Master of Public Health in Population and Family Health

* Certificate in Public Health Research Methods  

* Important Coursework: Epidemiology II; Spatial Epidemiology; Public Health GIS; Data Science I; Analysis of Categorical Data; Quantitative Data Analysis; Qualitative Data Analysis; Research Design and Data Collection; Public Health Program Planning

<br>

**Bryn Mawr College**  
*Bryn Mawr, PA*  
*Graduated: May 2016*

* Bachelor of Arts in Anthropology

* Minor in Health Studies

* Awards: Graduated magna cum laude; Department honors in Anthropology

* Thesis: *"You have a woman in your brewery!?"* Constructing Femininity and Belonging in the Brewing Industry

<br>

**School for International Training: International Honors Program**  
*Jan-May 2015*

* *Health and Community: Globalization, Culture and Care:* studied public health in India, South Africa and Brazil

## Research & Teaching Experience

**ICAP at Columbia University**  
**Research Assistant**  
*New York, NY*  
*June 2020 - Present*

* Supporting qualitative data analysis for the “PROvide Miner-friendly Services for Integrated TB/HIV Care in Lesotho (PROMISE)” Study
* Performed coding of 8 focus group transcripts and developed codebook for data analysis
* Performing data analysis utilizing Dedoose and contributing to the development of manuscripts for publication

<br>

**Mailman School of Public Health, Columbia University**  
**Lead Graduate Teaching Assistant**  
*New York, NY*  
*May 2020 - Present*

* One of two lead graduate teaching assistants for PUBH 6051, “Public Health Interventions”, a first-year graduate course covering the theory of public health interventions, program planning and evaluation, and systems thinking
* Supported faculty in developing course content, including contributing to syllabus development and assisting with the preparation of content for new online platforms (due to COVID-19)
* Managing a team of 10 TAs and providing administrative support to a teaching team of 5 faculty members, involving overseeing communication and grading for 400+ students

<br>

**University of California, Davis**  
**Resaerch Assistant**  
*Davis, CA*  
*May-Aug 2014*

* Closely read women’s health narratives and wrote concise summaries for an extensive literature review in the Chicana/o Studies Department
* Utilized the Social Sciences Research Network, the Hispanic American Periodicals Index, PubMed and other databases to find literature

## Professional Experience

**New York City Department of Health and Mental Hygiene**  
**Health Research Training Program (HRTP) Intern**  
*New York, NY*  
*June 2020 - October 2020*

* Collaborated with the “Boogie on the Boulevard” team to transition their community event to a virtual program 
* Managed data cleaning and tracking documents to ensure a smooth event planning process
* Effectively communicated with program partners and composed communications and marketing materials

<br>

**Living Beyond Breast Cancer**  
*Bala Cynwyd, PA*  
*Apr 2017-Sept 2019*

**Consultant**  
*Aug-Sept 2019*

* Developed workflow documentation and internal training resources for a team of 5 staff, and external instructional materials for 100+ social workers, for the launch of a quality of life grant and new online application platform

**Program Coordinator**  
*Jan-Aug 2019*

* Collaborated with Programs Team to develop and execute educational programming for people impacted by breast cancer: including conferences, live panel presentations, webinars and Twitter chats
* Effectively led interdepartmental team of 5-7 staff members to develop programming and content, ensured all team deliverables were met, recruited medical experts and prepped panelists for all webinars and Twitter chats
* Administered 2 grant programs for people diagnosed with breast cancer, serving 250+ recipients a year
* Managed, collected and input constituent data for educational and grant programs across databases and platforms  

**Program Assistant**  
*Apr 2017-Dec 2018*

* Successfully coordinated nutrition and cooking program for low-income women with breast cancer and increased attendance to 15-25 participants per class
* Developed and launched fitness class to complement nutrition programming, with attendance near 10-15

<br>

**Project HOME & Pennsylvania Health Access Network**  
**Franklin Fellow**  
*Philadelphia, PA*  
*Jan-Aug 2016*

* Collaborated with team of 5 to reach goal of 1000 signed petitions for the establishment of patient-centered medical homes and for the expansion of Medicaid to cover supportive housing services in Pennsylvania
* Collected stories of 6 Medicaid beneficiaries and homeless individuals about their experiences with housing instability and access to healthcare, to be shared with policymakers
* Edited 7 pieces of 30-60-minute footage into 2-3 minute clips and wrote blog posts about these stories to increase awareness about homelessness and difficulties in accessing healthcare
* Actively outreached to 400+ consumers via telephone, provided approximately 5% of these individuals with resources to access health care coverage and tracked communications in Salesforce

## Leadership Experience

**Food Justice Initiative**  
**President**  
*New York, NY*  
*Jan 2020 - Present*

* Leading meetings and managing a team of 6 students to organize professional, volunteer and academic events and programs on the topic of food and public health for the student body at the Mailman School of Public Health

<br>

**Partners in Health Engage**  
**Community Building Leader**  
*Haverford, PA*  
*Sept 2014-May 2016*

* Established a campus PIH Engage club and recruited 10 active members and a listserv of 80+
* Facilitated reading discussions at bi-weekly club meetings to educate community about global health concerns 
* Planned, developed and executed education events, such as a teach-in with a panel of professors during the Ebola outbreak in the fall of 2014

## Skills

**Data Analysis:** R, SPSS, GIS, Dedoose 

**Databases, CRMs and Event Planning:** Salesforce, Raiser's Edge, Luminate, Eventbrite  

**General:** Microsoft Office Suite (Excel, Word, PowerPoint, Access)
